name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
	     cd ~/myapp || exit

	     docker build -t myapp_new .

	     docker run -d --name myapp_new -p 9091:80 myapp_new

	     sleep 5

	     docker stop myapp || true
	     docker rm myapp || true

	     docker rename myapp_new myapp

	     docker run -d --name temp -p 9090:80 myapp
	     docker stop tempx
