name: Deploy to Multiple Servers

on:
  push:
    branches:
      - main

jobs:
  deploy-server-1:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server 1
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/myapp || exit
            git pull origin main
            docker stop myapp || true
            docker rm myapp || true
            docker build -t myapp .
            docker run -d --restart always --name myapp -p 9090:80 myapp

  deploy-server-2:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server 2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USER_2 }}
          key: ${{ secrets.EC2_KEY_2 }}
          script: |
            cd ~/myapp || exit
            git pull origin main
            docker stop myapp || true
            docker rm myapp || true
            docker build -t myapp .
            docker run -d --restart always --name myapp -p 9090:80 myapp
